name: Run JUnit CI

#Triger / Kapan Action-nya jalan
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up JDK 22
    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        java-version: '22'
        distribution: 'temurin'

    # Install Chrome and ChromeDriver
    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        wget https://chromedriver.storage.googleapis.com/$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    # Set up Gradle 8.10
    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.10

    # Make gradlew executable and run build & test
    - name: Build and Test
      run: |
        chmod +x gradlew
        ./gradlew build test
      env:
        JAVA_HOME: ${{ steps.setup-java.outputs.java-home }}
        CHROME_BIN: /usr/bin/google-chrome
        CHROMEDRIVER: /usr/local/bin/chromedriver

    - name: Archive test results
      uses: actions/upload-artifact@v4.3.0
      if: always() #always() # success() , failure(), canceled()
      with:
        name: cucumber reports
        path: target/cucumber-reports.html  # Path to test reports
